version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: finsight-postgres
    environment:
      POSTGRES_DB: finsight
      POSTGRES_USER: finsight
      POSTGRES_PASSWORD: finsight
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: finsight-redis
    ports:
      - "6379:6379"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: finsight-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: finsight-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend:
    build:
      context: ./backend
    container_name: finsight-backend
    depends_on:
      - postgres
      - redis
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/finsight
      SPRING_DATASOURCE_USERNAME: finsight
      SPRING_DATASOURCE_PASSWORD: finsight
      SPRING_DATA_REDIS_HOST: redis
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      AI_SERVICE_BASE_URL: http://ai-service:8001
      APP_JWT_SECRET: ${APP_JWT_SECRET:-bXktc3VwZXItc2VjcmV0LWtleS1mb3ItanVsdC1zaWduaW5nLTMyLWJ5dGVzLXBsdXM=}
    ports:
      - "8080:8080"

  ai-service:
    build:
      context: ./ai-service
    container_name: finsight-ai-service
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
    ports:
      - "8001:8001"

  frontend:
    build:
      context: ./frontend
    container_name: finsight-frontend
    depends_on:
      - backend
      - ai-service
    ports:
      - "5175:80"

  prometheus:
    image: prom/prometheus:v2.54.1
    container_name: finsight-prometheus
    depends_on:
      - backend
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.4
    container_name: finsight-grafana
    depends_on:
      - prometheus
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  pg_data:
  prometheus_data:
  grafana_data:
