package com.finsight.platform.service.impl;

import com.finsight.platform.domain.entity.Incident;
import com.finsight.platform.domain.entity.IncidentLog;
import com.finsight.platform.domain.entity.MonitoredService;
import com.finsight.platform.domain.enums.IncidentSeverity;
import com.finsight.platform.domain.enums.IncidentStatus;
import com.finsight.platform.domain.enums.LogLevel;
import com.finsight.platform.domain.enums.ServiceStatus;
import com.finsight.platform.dto.response.IncidentSimulationResponse;
import com.finsight.platform.events.model.IncidentCreatedEvent;
import com.finsight.platform.events.producer.IncidentEventProducer;
import com.finsight.platform.repository.IncidentLogRepository;
import com.finsight.platform.repository.IncidentRepository;
import com.finsight.platform.repository.MonitoredServiceRepository;
import com.finsight.platform.service.AuditService;
import com.finsight.platform.service.IncidentSimulationService;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.UUID;

import static com.finsight.platform.domain.enums.AuditAction.INCIDENT_CREATED;

@Service
public class IncidentSimulationServiceImpl implements IncidentSimulationService {

    private final MonitoredServiceRepository monitoredServiceRepository;
    private final IncidentRepository incidentRepository;
    private final IncidentLogRepository incidentLogRepository;
    private final IncidentEventProducer incidentEventProducer;
    private final AuditService auditService;

    public IncidentSimulationServiceImpl(
            MonitoredServiceRepository monitoredServiceRepository,
            IncidentRepository incidentRepository,
            IncidentLogRepository incidentLogRepository,
            IncidentEventProducer incidentEventProducer,
            AuditService auditService
    ) {
        this.monitoredServiceRepository = monitoredServiceRepository;
        this.incidentRepository = incidentRepository;
        this.incidentLogRepository = incidentLogRepository;
        this.incidentEventProducer = incidentEventProducer;
        this.auditService = auditService;
    }

    @Override
    @Transactional
    public IncidentSimulationResponse simulate(String scenario) {
        Map<String, ScenarioTemplate> templates = Map.of(
                "payment-failure", new ScenarioTemplate("Payment Service", "Payment transaction failures", "PAYMENT_GATEWAY_DOWN"),
                "database-failure", new ScenarioTemplate("Database Cluster", "Primary DB node unavailable", "DB_PRIMARY_DOWN"),
                "api-timeout", new ScenarioTemplate("Customer Service", "API timeout spike detected", "API_TIMEOUT"),
                "authentication-failure", new ScenarioTemplate("Authentication Service", "Login failures increased", "AUTH_FAILURE"),
                "memory-leak", new ScenarioTemplate("Notification Service", "Memory leak pattern identified", "OOM_RISK")
        );

        ScenarioTemplate selected = templates.getOrDefault(scenario, templates.get("api-timeout"));

        MonitoredService service = monitoredServiceRepository.findByName(selected.serviceName())
                .orElseGet(() -> createService(selected.serviceName()));

        service.setStatus(ServiceStatus.DEGRADED);
        service.setLatencyMs(BigDecimal.valueOf(2200));
        service.setCpuUsage(BigDecimal.valueOf(89));
        service.setMemoryUsage(BigDecimal.valueOf(82));
        service.setRequestsPerSec(BigDecimal.valueOf(520));
        service.setAvailabilityPct(BigDecimal.valueOf(97.20));
        monitoredServiceRepository.save(service);

        Incident incident = new Incident();
        incident.setIncidentKey("INC-" + (100000 + (int) (Math.random() * 900000)));
        incident.setTitle(selected.title());
        incident.setDescription("Synthetic scenario generated by Incident Simulator: " + selected.title());
        incident.setService(service);
        incident.setStatus(IncidentStatus.OPEN);
        incident.setSeverity(IncidentSeverity.MEDIUM);
        incident.setAffectedUsers(1200);
        incident.setResponseTimeMs(2600);
        incident.setErrorFrequency(BigDecimal.valueOf(64.5));
        incident = incidentRepository.save(incident);

        List<IncidentLog> logs = List.of(
                buildLog(incident, service, LogLevel.ERROR, selected.errorCode(), "java.net.SocketTimeoutException", "Circuit open for upstream dependency"),
                buildLog(incident, service, LogLevel.ERROR, selected.errorCode(), "java.sql.SQLException", "Connection pool exhausted while retrying"),
                buildLog(incident, service, LogLevel.WARN, selected.errorCode(), null, "Fallback path activated with partial response")
        );
        incidentLogRepository.saveAll(logs);

        incidentEventProducer.publishIncidentCreated(
                new IncidentCreatedEvent(incident.getId(), scenario, OffsetDateTime.now())
        );

        auditService.record(INCIDENT_CREATED, "Simulated incident " + incident.getIncidentKey(), null);

        return new IncidentSimulationResponse(
                incident.getId(),
                incident.getIncidentKey(),
                scenario,
                "Simulation accepted. Incident pipeline has been triggered."
        );
    }

    private MonitoredService createService(String name) {
        MonitoredService service = new MonitoredService();
        service.setName(name);
        service.setEnvironment("PROD");
        service.setStatus(ServiceStatus.HEALTHY);
        return monitoredServiceRepository.save(service);
    }

    private IncidentLog buildLog(
            Incident incident,
            MonitoredService service,
            LogLevel level,
            String errorCode,
            String exception,
            String message
    ) {
        IncidentLog log = new IncidentLog();
        log.setIncident(incident);
        log.setService(service);
        log.setEnvironment("PROD");
        log.setLogLevel(level);
        log.setCorrelationId(UUID.randomUUID().toString());
        log.setResponseTimeMs(incident.getResponseTimeMs());
        log.setErrorCode(errorCode);
        log.setException(exception);
        log.setMessage(message);
        return log;
    }

    private record ScenarioTemplate(String serviceName, String title, String errorCode) {
    }
}
